### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by HernanChaz** [Patalin/Flip-text-animation#1]
Hello, correct me if i'm wrong but I think  class="loading" should be class="waviy"
 
and 

animation-delay: calc(.2s * var(--i)) 
should be 
animation-delay: calc(.2s * var(--letter))

**Comment by Patalin** [comment]
Your right, i did a mistake there

**Comment by Patalin** [comment]
I just modified the code, now it should work. Thank you so much for letting me know

**Comment by HernanChaz** [comment]
> I just modified the code, now it should work. Thank you so much for letting me know

Thanks to you for an amazing work!
